# Generated by Django 5.2.15 on 2026-06-10 17:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_category_options_alter_product_options_and_more'),
        ('commandes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitem',
            options={'verbose_name': 'Article de panier', 'verbose_name_plural': 'Articles de panier'},
        ),
        migrations.AlterModelOptions(
            name='orderstatushistory',
            options={'ordering': ['created_at'], 'verbose_name': 'Historique de statut', 'verbose_name_plural': 'Historiques de statut'},
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='order',
            name='reference',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', '-created_at'], name='commandes_o_user_id_fb2e4c_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', '-created_at'], name='commandes_o_status_52cfda_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order'], name='commandes_o_order_i_eec58f_idx'),
        ),
        migrations.AddIndex(
            model_name='orderstatushistory',
            index=models.Index(fields=['order', 'created_at'], name='commandes_o_order_i_34db51_idx'),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(fields=('cart', 'product'), name='unique_cartitem_cart_product'),
        ),
        migrations.AlterModelTable(
            name='orderstatushistory',
            table='commandes_order_status_history',
        ),
    ]
