# Generated by Django 6.0.6 on 2026-06-11 17:23

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commandes', '0002_alter_cartitem_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoyaltyTier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(help_text='Nom du palier (Bronze, Silver, Gold…).', max_length=50, unique=True)),
                ('min_points', models.PositiveIntegerField(default=0, help_text='Points cumulés (lifetime) minimum requis pour accéder à ce palier.')),
                ('min_solde', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Dépenses totales minimum (FCFA) — critère informatif.', max_digits=12)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Réduction automatique appliquée sur les commandes (%).', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('cashback_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Cashback reversé dans le wallet après livraison (%).', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('points_multiplier', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Multiplicateur de points gagnés (1.0 = standard, 2.0 = double).', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('color', models.CharField(blank=True, default='#CD7F32', help_text='Code couleur CSS du palier (ex : #CD7F32 pour Bronze).', max_length=20)),
                ('icon', models.CharField(blank=True, default='shield', help_text="Nom d'icône frontend (ex : shield-bronze).", max_length=50)),
                ('is_default', models.BooleanField(default=False, help_text='Palier attribué automatiquement aux nouveaux utilisateurs. Un seul autorisé.')),
            ],
            options={
                'verbose_name': 'Palier de fidélité',
                'verbose_name_plural': 'Paliers de fidélité',
                'db_table': 'loyalty_tiers',
                'ordering': ['min_points'],
            },
        ),
        migrations.CreateModel(
            name='TierChangeLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('from_tier', models.CharField(blank=True, help_text='Nom du palier précédent (vide si premier palier).', max_length=50)),
                ('to_tier', models.CharField(help_text='Nom du nouveau palier.', max_length=50)),
                ('reason', models.TextField(blank=True, help_text='Explication du changement (points, dépenses, ajustement admin…).')),
                ('user', models.ForeignKey(help_text='Utilisateur dont le palier a changé.', on_delete=django.db.models.deletion.CASCADE, related_name='tier_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Changement de palier',
                'verbose_name_plural': 'Changements de palier',
                'db_table': 'loyalty_tier_change_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoyaltyEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('points_delta', models.IntegerField(help_text='Variation de points : positif = gain, négatif = dépense/expiration.')),
                ('new_points_balance_after', models.PositiveIntegerField(help_text='Snapshot du solde de points immédiatement après ce mouvement.')),
                ('reason', models.CharField(choices=[('purchase', 'Achat'), ('refund', 'Remboursement'), ('referral_bonus', 'Bonus parrainage'), ('first_purchase', 'Premier achat'), ('birthday_bonus', 'Bonus anniversaire'), ('points_expiry', 'Expiration de points'), ('admin_adjustment', 'Ajustement administrateur'), ('order_discount', 'Réduction commande')], db_index=True, help_text="Catégorie de l'événement.", max_length=30)),
                ('expires_at', models.DateTimeField(blank=True, help_text="Date d'expiration des points gagnés (uniquement pour les gains PURCHASE).", null=True)),
                ('description', models.TextField(blank=True, help_text="Description lisible de l'événement pour l'historique client.")),
                ('order', models.ForeignKey(blank=True, help_text='Commande associée (si applicable).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loyalty_events', to='commandes.order')),
                ('user', models.ForeignKey(help_text='Utilisateur concerné par cet événement.', on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Événement de fidélité',
                'verbose_name_plural': 'Événements de fidélité',
                'db_table': 'loyalty_events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='loyalty_eve_user_id_032f36_idx'), models.Index(fields=['reason'], name='loyalty_eve_reason_84e279_idx'), models.Index(fields=['expires_at'], name='loyalty_eve_expires_e59047_idx'), models.Index(fields=['order'], name='loyalty_eve_order_i_73271c_idx')],
            },
        ),
        migrations.CreateModel(
            name='LoyaltyProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('points_balance', models.PositiveIntegerField(default=0, help_text='Solde de points disponibles pour dépense ou expiration.')),
                ('total_points_earned', models.PositiveIntegerField(default=0, help_text='Total de points gagnés (lifetime). Jamais décrémenté. Sert au calcul de palier.')),
                ('total_solde', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Dépenses cumulées sur commandes livrées (FCFA).', max_digits=12)),
                ('birth_date', models.DateField(blank=True, help_text="Date de naissance pour le bonus d'anniversaire annuel.", null=True)),
                ('referral_code', models.CharField(blank=True, db_index=True, help_text='Code de parrainage unique auto-généré (format REF-XXXXXXXX).', max_length=20, unique=True)),
                ('referred_by', models.ForeignKey(blank=True, help_text='Profil de fidélité du parrain (si ce client a été parrainé).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='fidelites.loyaltyprofile')),
                ('user', models.OneToOneField(help_text='Utilisateur propriétaire de ce profil.', on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_profile', to=settings.AUTH_USER_MODEL)),
                ('tier', models.ForeignKey(blank=True, help_text='Palier actuel. Assigné automatiquement à la création puis recalculé.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='profiles', to='fidelites.loyaltytier')),
            ],
            options={
                'verbose_name': 'Profil de fidélité',
                'verbose_name_plural': 'Profils de fidélité',
                'db_table': 'loyalty_profiles',
                'indexes': [models.Index(fields=['tier'], name='loyalty_pro_tier_id_8edb83_idx'), models.Index(fields=['referral_code'], name='loyalty_pro_referra_8b229b_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('points_balance__gte', 0)), name='loyalty_points_balance_non_negative')],
            },
        ),
    ]
