# Generated by Django 5.2.15 on 2026-06-11 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fidelites', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='loyaltyprofile',
            name='loyalty_pro_referra_8b229b_idx',
        ),
        migrations.RemoveField(
            model_name='loyaltyprofile',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='loyaltyprofile',
            name='referral_code',
        ),
        migrations.RemoveField(
            model_name='loyaltyprofile',
            name='referred_by',
        ),
        migrations.RemoveField(
            model_name='loyaltytier',
            name='cashback_percent',
        ),
        migrations.RemoveField(
            model_name='loyaltytier',
            name='color',
        ),
        migrations.RemoveField(
            model_name='loyaltytier',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='loyaltytier',
            name='is_default',
        ),
        migrations.RemoveField(
            model_name='loyaltytier',
            name='points_multiplier',
        ),
    ]
