# Generated by Django 5.2.15 on 2026-06-10 17:41

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_category_is_active_alter_category_slug_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Catégorie', 'verbose_name_plural': 'Catégories'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at'], 'verbose_name': 'Produit', 'verbose_name_plural': 'Produits'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['-is_primary'], 'verbose_name': 'Image Produit', 'verbose_name_plural': 'Images Produit'},
        ),
        migrations.AlterModelOptions(
            name='productvariant',
            options={'ordering': ['name'], 'verbose_name': 'Variante Produit', 'verbose_name_plural': 'Variantes Produit'},
        ),
        migrations.AddField(
            model_name='product',
            name='count_favorites',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='Nombre de favoris (dénormalisé, recalculé par signal).'),
        ),
        migrations.AddField(
            model_name='product',
            name='count_ratings',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='Nombre de notes (dénormalisé, recalculé par signal).'),
        ),
        migrations.AddField(
            model_name='product',
            name='note_produit',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, help_text='Note moyenne du produit (dénormalisé, recalculé par signal).', max_digits=3),
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='catalog.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Favori',
                'verbose_name_plural': 'Favoris',
                'db_table': 'favorites_favorites',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='favorites_f_user_id_57485f_idx'), models.Index(fields=['product', '-created_at'], name='favorites_f_product_3f3b82_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'product'), name='unique_favorite_user_product')],
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('score', models.PositiveSmallIntegerField(help_text='Note de 0 à 5 étoiles', validators=[django.core.validators.MinValueValidator(0, message='La note minimale est 0.'), django.core.validators.MaxValueValidator(5, message='La note maximale est 5.')])),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='catalog.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Notes',
                'db_table': 'ratings_ratings',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['product', '-updated_at'], name='ratings_rat_product_6d0546_idx'), models.Index(fields=['user', '-updated_at'], name='ratings_rat_user_id_afaa93_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'product'), name='unique_rating_user_product')],
            },
        ),
    ]
