# Generated by Django 6.0.6 on 2026-06-11 17:23

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0004_alter_category_options_alter_product_options_and_more'),
        ('commandes', '0002_alter_cartitem_options_and_more'),
        ('fidelites', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=500)),
                ('image', models.ImageField(help_text='Image de la bannière (optimisée pour le type).', upload_to='banners/%Y/%m/')),
                ('cta_label', models.CharField(blank=True, help_text="Texte du bouton d'action.", max_length=100)),
                ('cta_url', models.URLField(blank=True, help_text='URL de destination du clic.', max_length=500)),
                ('banner_type', models.CharField(choices=[('carousel', 'Carrousel'), ('popup', 'Popup'), ('hero', 'Hero / En-tête'), ('side_banner', 'Bannière latérale')], db_index=True, default='hero', max_length=20)),
                ('position', models.PositiveIntegerField(default=0, help_text="Ordre d'affichage (0 = premier).")),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Bannière',
                'verbose_name_plural': 'Bannières',
                'db_table': 'promotions_banners',
                'ordering': ['banner_type', 'position', '-created_at'],
                'indexes': [models.Index(fields=['banner_type', 'is_active'], name='promotions__banner__dd7c69_idx')],
            },
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('code', models.CharField(db_index=True, help_text='Code promo saisi par le client. Auto-généré si vide.', max_length=50, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description interne de la campagne.')),
                ('type', models.CharField(choices=[('percentage', 'Pourcentage (%)'), ('fixed_amount', 'Montant fixe (FCFA)'), ('free_shipping', 'Livraison gratuite')], default='percentage', max_length=20)),
                ('value', models.DecimalField(decimal_places=2, help_text='Valeur de la réduction (%, FCFA).', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('number_times_used', models.PositiveIntegerField(default=0, editable=False, help_text="Compteur d'utilisations (incrémenté atomiquement).")),
                ('max_uses', models.PositiveIntegerField(default=0, help_text='Quota global maximum (0 = illimité).')),
                ('max_uses_per_user', models.PositiveIntegerField(default=1, help_text="Quota d'utilisation par utilisateur.")),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Montant minimum de commande (FCFA).', max_digits=12)),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Plafond de réduction pour le type pourcentage (FCFA).', max_digits=12, null=True)),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Date de début de validité.')),
                ('expires_at', models.DateTimeField(blank=True, help_text="Date d'expiration. Null = pas d'expiration.", null=True)),
                ('applicable_categories', models.ManyToManyField(blank=True, help_text='Catégories éligibles (vide = toutes).', related_name='promo_codes', to='catalog.category')),
                ('applicable_products', models.ManyToManyField(blank=True, help_text='Produits éligibles (vide = tous).', related_name='promo_codes', to='catalog.product')),
                ('restricted_to_tiers', models.ManyToManyField(blank=True, help_text='Paliers de fidélité autorisés (vide = tous).', related_name='restricted_promo_codes', to='fidelites.loyaltytier')),
            ],
            options={
                'verbose_name': 'Code promo',
                'verbose_name_plural': 'Codes promo',
                'db_table': 'promotions_promo_codes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PromoUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('discount_applied', models.DecimalField(decimal_places=2, help_text='Montant de réduction effectivement appliqué.', max_digits=12)),
                ('order', models.ForeignKey(help_text='Commande sur laquelle le code a été appliqué.', on_delete=django.db.models.deletion.PROTECT, related_name='promo_usages', to='commandes.order')),
                ('promo_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usages', to='promotions.promocode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='promo_usages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Utilisation code promo',
                'verbose_name_plural': 'Utilisations codes promo',
                'db_table': 'promotions_promo_usages',
            },
        ),
        migrations.CreateModel(
            name='Soldes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('sale_price', models.DecimalField(decimal_places=2, help_text='Prix soldé.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('original_price', models.DecimalField(decimal_places=2, editable=False, help_text='Prix original snapshot au moment de la création.', max_digits=12)),
                ('quota_stock_limit', models.PositiveIntegerField(blank=True, help_text='Quota maximum de ventes au prix soldé (null = illimité).', null=True)),
                ('product_sold_count', models.PositiveIntegerField(default=0, editable=False, help_text='Nombre de ventes effectuées (incrémenté atomiquement).')),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Début de la vente flash.')),
                ('ends_at', models.DateTimeField(help_text='Fin de la vente flash.')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soldes', to='catalog.product')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='soldes', to='catalog.productvariant')),
            ],
            options={
                'verbose_name': 'Solde',
                'verbose_name_plural': 'Soldes',
                'db_table': 'promotions_soldes',
                'ordering': ['-starts_at'],
            },
        ),
        migrations.AddIndex(
            model_name='promocode',
            index=models.Index(fields=['code'], name='promotions__code_1f5548_idx'),
        ),
        migrations.AddIndex(
            model_name='promocode',
            index=models.Index(fields=['is_active', 'starts_at', 'expires_at'], name='promotions__is_acti_5407c2_idx'),
        ),
        migrations.AddIndex(
            model_name='promousage',
            index=models.Index(fields=['promo_code', 'user'], name='promotions__promo_c_bba677_idx'),
        ),
        migrations.AddIndex(
            model_name='promousage',
            index=models.Index(fields=['order'], name='promotions__order_i_58555c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='promousage',
            unique_together={('promo_code', 'user', 'order')},
        ),
        migrations.AddIndex(
            model_name='soldes',
            index=models.Index(fields=['is_active', 'starts_at', 'ends_at'], name='promotions__is_acti_95f668_idx'),
        ),
        migrations.AddIndex(
            model_name='soldes',
            index=models.Index(fields=['product'], name='promotions__product_57944c_idx'),
        ),
    ]
