# Generated by Django 5.2.15 on 2026-06-11 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promocode',
            name='max_discount_amount',
        ),
        migrations.RemoveField(
            model_name='promocode',
            name='max_uses',
        ),
        migrations.RemoveField(
            model_name='promocode',
            name='max_uses_per_user',
        ),
        migrations.RemoveField(
            model_name='promocode',
            name='min_order_amount',
        ),
    ]
