# Generated by Django 5.2.15 on 2026-06-10 17:41

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commandes', '0002_alter_cartitem_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayDunyaWebhookLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('token', models.CharField(db_index=True, help_text='Token de la transaction PayDunya.', max_length=100)),
                ('payload', models.JSONField(help_text='Payload JSON brut reçu.')),
                ('status_traitement', models.CharField(choices=[('processed', 'Traité avec succès'), ('duplicate', 'Doublon ignoré'), ('error', 'Erreur lors du traitement')], max_length=20)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Log webhook PayDunya',
                'verbose_name_plural': 'Logs webhooks PayDunya',
                'db_table': 'payments_webhook_logs',
                'indexes': [models.Index(fields=['token'], name='payments_we_token_b9ab16_idx'), models.Index(fields=['-created_at'], name='payments_we_created_264f99_idx')],
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('status', models.CharField(choices=[('active', 'Actif'), ('suspendu', 'Suspendu'), ('blocked', 'Bloqué')], db_index=True, default='active', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Portefeuille',
                'verbose_name_plural': 'Portefeuilles',
                'db_table': 'payments_wallets',
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('transaction_type', models.CharField(choices=[('deposit', 'Dépôt'), ('withdrawal', 'Retrait'), ('payment', 'Paiement'), ('refund', 'Remboursement'), ('cashback', 'Cashback')], db_index=True, max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('reference', models.CharField(db_index=True, help_text='Référence unique interne (UUID ou token).', max_length=100, unique=True)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('success', 'Réussi'), ('failed', 'Échoué'), ('cancelled', 'Annulé')], db_index=True, default='pending', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Données additionnelles (token PayDunya, etc.)')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_transactions', to='commandes.order')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='paiements.wallet')),
            ],
            options={
                'verbose_name': 'Transaction de portefeuille',
                'verbose_name_plural': 'Transactions de portefeuille',
                'db_table': 'payments_wallet_transactions',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('provider', models.CharField(choices=[('paydunya', 'PayDunya'), ('stripe', 'Stripe')], db_index=True, max_length=20)),
                ('payment_type', models.CharField(choices=[('order_payment', 'Paiement de commande'), ('wallet_topup', 'Recharge de portefeuille'), ('direct_payment', 'Paiement direct (sans compte)'), ('admin_withdraw', 'Retrait administrateur')], db_index=True, max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('success', 'Réussi'), ('failed', 'Échoué'), ('cancelled', 'Annulé'), ('refunded', 'Remboursé')], db_index=True, default='pending', max_length=20)),
                ('reference_externe', models.CharField(blank=True, help_text='Token PayDunya ou autre référence externe.', max_length=100)),
                ('webhook_token', models.CharField(blank=True, help_text='Token utilisé dans le callback pour idempotence.', max_length=100, null=True, unique=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('order', models.ForeignKey(blank=True, help_text='Commande associée (null pour les recharges wallet).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='commandes.order')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'db_table': 'payments_payments',
                'indexes': [models.Index(fields=['order'], name='payments_pa_order_i_a64b65_idx'), models.Index(fields=['status', '-created_at'], name='payments_pa_status_dfc04c_idx'), models.Index(fields=['reference_externe'], name='payments_pa_referen_c0a35d_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='wallet',
            index=models.Index(fields=['user'], name='payments_wa_user_id_f3548a_idx'),
        ),
        migrations.AddIndex(
            model_name='wallet',
            index=models.Index(fields=['status'], name='payments_wa_status_9c61bd_idx'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['wallet', '-created_at'], name='payments_wa_wallet__dc01e7_idx'),
        ),
    ]
