# Generated by Django 6.0.6 on 2026-06-11 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalTransaction',
            fields=[
            ],
            options={
                'verbose_name': 'Transaction Globale',
                'verbose_name_plural': 'Transactions Globales',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('paiements.payment',),
        ),
        migrations.AddField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Utilisateur lié à la transaction (pour traçabilité globale).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to=settings.AUTH_USER_MODEL),
        ),
    ]
